### ISSUE TITLE
Any plans to read Blender 3.1 BLEND files?

### ISSUE THREAD

**Issue by tommai78101** [homacs/org.cakelab.blender.io#2]
Blender 3.1 is released. Was wondering if there are any plans to update the project to support 3.1 BLEND files?

![image](https://user-images.githubusercontent.com/6444116/161412138-65cc821d-845a-45ee-9ba7-c487ccf084fb.png)

OS:  Windows 10 64-bit.

Blender 3.1  "cube.blend" file (brand new Blender scene).

**Comment by homacs** [comment]
Simply missed it. I'll have a look this weekend.

**Comment by homacs** [comment]
done

**Comment by tommai78101** [comment]
Thank you.
